(source gnu)
(source melpa)

(depends-on "cask")
(depends-on "f")
(depends-on "s")
(depends-on "use-package")
(depends-on "bind-key")
(depends-on "dash")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "use-package")

(depends-on "editorconfig")
(depends-on "flycheck-cask")
(depends-on "htmlize")
(depends-on "idle-highlight-mode")
(depends-on "popwin")
(depends-on "sx")
(depends-on "smartparens")
(depends-on "smart-mode-line")
(depends-on "writeroom-mode")
(depends-on "tern")
(depends-on "wgrep")
(depends-on "avy")
(depends-on "dumb-jump")

(depends-on "flycheck")
(depends-on "flycheck-ledger")

(depends-on "ivy")
(depends-on "counsel")
(depends-on "swiper")
(depends-on "helm-dash")

(depends-on "magit")
(depends-on "gist")
(depends-on "git-gutter")

(depends-on "projectile")
(depends-on "perspective")

(depends-on "yasnippet")

(depends-on "company")
(depends-on "company-tern")
(depends-on "company-emoji")
(depends-on "company-go")

(depends-on "web-mode")
(depends-on "emmet-mode")
(depends-on "js2-mode")
(depends-on "coffee-mode")
(depends-on "fish-mode")
(depends-on "less-css-mode")
(depends-on "stylus-mode")
(depends-on "scss-mode")
(depends-on "php-mode")
(depends-on "markdown-mode")
(depends-on "lua-mode")
(depends-on "dockerfile-mode")
(depends-on "puppet-mode")
(depends-on "yaml-mode")
(depends-on "ruby-mode")
(depends-on "robe")
(depends-on "haskell-mode")
(depends-on "intero")
(depends-on "rainbow-mode")
(depends-on "rainbow-delimiters")
(depends-on "ledger-mode")
(depends-on "swift-mode")

(depends-on "go-mode")

(depends-on "rust-mode")
(depends-on "racer")

(depends-on "evil")
(depends-on "evil-leader")
(depends-on "evil-search-highlight-persist")
(depends-on "evil-commentary")
(depends-on "evil-snipe")
(depends-on "evil-surround")
(depends-on "evil-matchit")
(depends-on "evil-visual-mark-mode")

(depends-on "request-deferred")
